### ISSUE TITLE
error unsupported type "Qt3DRender::QAbstractTexture*"

### ISSUE THREAD

**Issue by filipdns** [tripolskypetr/simpleqml3d#1]
Trying your example with QT5.11.2 MSVC2015 64bit on windows, I receive error:

qrc:/IronMan.qml:25:22: Invalid property assignment: unsupported type "Qt3DRender::QAbstractTexture*"

do you know why?...

`        material: DiffuseMapMaterial {
            id: material
            diffuse: "qrc:/man.png" //Path to the texture image. You can get it by converting .tga to .png
            specular: Qt.rgba( 0.2, 0.2, 0.2, 1.0 )
            shininess: 2.0
        }`

**Comment by tripolskypetr** [comment]
fixed
https://github.com/tripolskypetr/simpleqml3d/commit/0d78480b69ffb65d31506e2b21292c60a8a6457c
